apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "25"
  creationTimestamp: "2025-07-15T11:06:00Z"
  finalizers:
  - argoproj.io/finalizer
  generation: 2
  labels:
    app: argocd
  name: argocd
  namespace: openshift-gitops
  resourceVersion: "173227"
  uid: 8c89a63a-678d-4932-aed6-9c7ecf8f3f03
spec:
  applicationInstanceLabelKey: rht-gitops.com/openshift-gitops
  applicationSet:
    webhookServer:
      ingress:
        enabled: false
      route:
        enabled: false
  controller:
    appSync: 30s
    processors: {}
    sharding: {}
  extraConfig:
    accounts.mark: 'apiKey, login'
    resource.customizations.health.PersistentVolumeClaim: |
      hs = {}
      if obj.status ~= nil then
        if obj.status.phase ~= nil then
          if obj.status.phase == "Pending" then
            hs.status = "Healthy"
            hs.message = obj.status.phase
            return hs
          end
          if obj.status.phase == "Bound" then
            hs.status = "Healthy"
            hs.message = obj.status.phase
            return hs
          end
        end
      end
      hs.status = "Progressing"
      hs.message = "Waiting for PVC"
      return hs
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  ha:
    enabled: false
  initialSSHKnownHosts: {}
  monitoring:
    enabled: false
  notifications:
    enabled: true
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  rbac:
    defaultPolicy: role:admin
    policy: |
      g, system:cluster-admins, role:admin
    scopes: '[groups]'
  redis: {}
  repo: {}
  resourceExclusions: |
    - apiGroups:
        - tekton.dev
      clusters:
        - '*'
      kinds:
        - TaskRun
        - PipelineRun
  resourceHealthChecks:
  - check: |
      local health_status = {}
      health_status.status = "Progressing"
      health_status.message = "Waiting for status update."
      if obj.status ~= nil and obj.status.conditions ~= nil then
        local status_true = 0
        local status_false = 0
        local status_unknown = 0
        health_status.message = ""
        for i, condition in pairs(obj.status.conditions) do
          if condition.status == "True" and (condition.type == "Ready") then
            status_true = status_true + 1
          elseif condition.status == "False" or condition.status == "Unknown" then
            if condition.status == "False" then
              status_false = status_false + 1
            else
              status_unknown = status_unknown + 1
            end
          end
        end
        if status_true >= 1 and status_false == 0 and status_unknown == 0 then
          health_status.message = "Inference Service is healthy."
          health_status.status = "Healthy"
          return health_status
        end
      end
      return health_status
    group: serving.kserve.io
    kind: InferenceService
  - check: |
      hs = {}
      hs.status = "Healthy"
      return hs
    group: networking.k8s.io
    kind: Ingress
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    route:
      enabled: true
      tls:
        termination: reencrypt
    service:
      type: ""
  tls:
    ca: {}
status:
  applicationController: Running
  applicationSetController: Running
  host: argocd-server-openshift-gitops.apps.cluster-w9tn8.w9tn8.sandbox1665.opentlc.com
  notificationsController: Running
  phase: Available
  redis: Running
  repo: Running
  server: Running
  sso: Unknown
